name: deploy to EC2
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    name: deploying to EC2 server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code basevb
        uses: actions/checkout@v2
      
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
         host: 13.233.64.77
         username: ubuntu
         key: ${{ secrets.KEY }}
         port: 22
         script: |
          ls -la
          # 1. Install Node.js & npm (one-time setup)
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt install -y nodejs

          # 2. Clone the repo (if not already cloned)
          git clone https://github.com/PratikshaPrachi/ci-cd-1122.git 
          cd  ci-cd-1122/my-ci-app
          git pull origin main
          npm install
          npm run build
          sudo lsof -ti :3000 | xargs -r sudo kill -9
          npm start
          nohup npm start > out.log 2>&1 &
          
