name: deploy to EC2
on:
  push:
    branches: ["main"]
jobs:
  deploy:
    name: deploying to EC2 server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code basevb
        uses: actions/checkout@v2
      
      - name: Execute remote SSH commands using SSH key
        uses: appleboy/ssh-action@v1
        with:
         host: 13.204.86.118
         username: ubuntu
         key: ${{ secrets.KEY }}
         port: 22
         script: whoami